name: ade_flutterwave_working_version
description: A working Flutterwave payment gateway for Flutter apps.
homepage: https://github.com/adeflutterdev/flutterwave_working_version

version: 0.0.3+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.7.0
  loading_overlay: ^0.3.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - files/
