name: ade_flutterwave_working_version
description: Flutterwave payment gateway for flutter that works fine.
homepage: https://github.com/adeleyeayodeji/ade_flutterwave_working_version

version: 0.0.2+2

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  loading_overlay: ^0.3.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - files/
